steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["ci"]
  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
  # Deploy
  - name: gcr.io/uppgift-2-blog/firebase
    args: ["deploy", "--project=uppgift-2-blog"]
