steps:
  # Install
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "-w blog"]
  # Build
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build", "-w blog"]
  # Deploy
  - name: gcr.io/uppgift-2-blog/firebase
    args: ["deploy"]
